### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by hieubagiang** [sr-henry/league-hack#2]
Hello, I cant run program because i dont have opencv_world452.ddl, opencv_world452d.ddl

**Comment by YMY1666527646** [comment]
I compiled it、I have the same problem as you. There is no OpenCV_ World452 file

**Comment by YMY1666527646** [comment]
> 您好，我无法运行程序，因为我没有 opencv_world452.ddl、opencv_world452d.ddl

https://github.com/sr-henry/league-hack/tree/73b2b9bd04c6b2997b1d85e81512f35848e71976/league-hack/dependencies/opencv

**Comment by sr-henry** [comment]
Hi, you can download this dll from this repo and place in system32 folder or install opencv in your pc
